### PR TITLE
ext/doc fixes

### PR DESCRIPTION
**Pull request by r3nat**
http://www.phpdoc.org/docs/latest/guides/types.html#class-name says, that class names without slashes are relative

### CODE REVIEW

**Comment by avalanche123** [comment]
does this actually prevent ide autocompletion for you? Because we are not using phpdocumentor for the api docs generation

**Comment by r3nat** [comment]
yep

image

**Comment by avalanche123** [comment]
kk, I'll merge this in after I confirm that generated docs still look good, thanks!

**Comment by avalanche123** [comment]
merged and pushed, thanks!

**Pull request closed without merging**
