### PR TITLE
Add the Travis badge in the readme

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Comment by stof** [comment]
You need to enable the hook in the repo for that to be useful though

**Comment by avalanche123** [comment]
Yeah,  I'll merge this in as soon as I configure Travis, thanks!

**Comment by stof** [comment]
@avalanche123 this should only require a click on a button in the Travis UI (plus eventually forcing a sync of the list of repos if needed)

**Comment by avalanche123** [comment]
done

**Pull request merged**
