### PR TITLE
test: PHP-119 - Driver crash getting column type

### PR DESCRIPTION
**Pull request by mikefero**
This issue was isolated to PHP v5.6.x; however this test can be utilized to ensure correctness for all supported PHP versions.

### CODE REVIEW

**Comment by mpenick** [comment]
My concern is the default schema can vary on different versions of C* so this might not test anything. I wonder if there some builtin test custom type we can use for this test?

**Comment by mikefero** [comment]
True! Let me dig into more closely and get the exact problem type that was causing the issue in the first place.

**Comment by mikefero** [comment]
Updated original test with a NULL check and created additional test for root cause; datastax/cpp-driver#345.

**Comment by mpenick** [comment]
+1 squash and merge.

**Pull request merged**
