### PR TITLE
Update the Composer instructions

### PR DESCRIPTION
**Pull request by stof**
These instructions avoid people to make manual edition of the composer.json file.

Once the library is stable, you can even remove the version entirely and Composer will guess the best semver constraint

### CODE REVIEW

**Comment by avalanche123** [comment]
Thanks @stof!

I will also need your help with reviews and feedback on this driver in the future.
Can you please sign the CLA so I can merge this in?

Cheers!

**Comment by stof** [comment]
@avalanche123 what would be the way to discuss with you about some initial feedback ? Twitter is not the appropriate format

**Comment by avalanche123** [comment]
@stof irc freenode #datastax-drivers, or a Jira issue

**Comment by avalanche123** [comment]
oh, also [the mailing list](https://groups.google.com/a/lists.datastax.com/forum/#!forum/php-driver-user). That might be a more appropriate forum.

**Pull request merged**
